<?php

return [
    'name' => 'W3Options',

    'option_field_types' => array(
        'ace_editor' => array(
            'type' => 'ace_editor',
            'mode' => 'javascript',
            'theme' => 'monokai',
            'options' => array(
                'minLines' => 12, 
                'maxLines' => 30
            ),
        ),
        'background' => array(
                        'type' => 'background',
                        'default' => '',
                        'select2' => '',
                        'background-color' => 'true',
                        'background-repeat' => 'true',
                        'background-attachment' => 'true',
                        'background-position' => 'true',
                        'background-image' => 'true',
                        'background-clip' => 'false',
                        'background-origin' => 'false',
                        'background-size' => 'true',
                        'preview_media' => 'false',
                        'preview' => 'true',
                        'preview_height' => '200px',
                        'transparent' => 'true',
        ),
        'border' => array(
                        'type' => 'border',
                        'default' => '',
                        'select2' => '',
                        'validate' => 'color',
                        'all' => 'true',
                        'left' => 'true',
                        'right' => 'true',
                        'top' => 'true',
                        'bottom' => 'true',
                        'style' => 'true',
                        'color' => 'true',
                        'color_alpha' => 'false',
        ),
        'box_shadow' => array(
                        'type' => 'box_shadow',
                        'default' => '',
                        'preview_color' => '#f1f1f1',
                        'inset-shadow' => 'true',
                        'drop-shadow' => 'true',
        ),
        'button_set' => array(
                        'type' => 'button_set',
                        'options' => '',
                        'default' => '',
                        'multi' => 'false',
        ),
        'checkbox' => array(
                        'type' => 'checkbox',
                        'options' => '',
                        'default' => '',
        ),
        'color_gradient' => array(
                        'type' => 'color_gradient',
                        'default' => '',
                        'validate' => '',
                        'transparent' => 'true',
                        'preview' => 'false',
                        'preview_height' => '150px',
                        'color_alpha' => 'false',
                        'gradient-type' => 'false',
                        'gradient-reach' => 'false',
                        'gradient-angle' => 'false',
        ),
        'color_palette' => array(
                        'type' => 'color_palette',
                        'default' => '',
                        'options' => '',
        ),
        'color_rgba' => array(
                        'type' => 'color_rgba',
                        'default' => '',
                        'options' => '',
        ),
        'color' => array(
                        'type' => 'color',
                        'transparent' => 'true',
                        'validate' => '',
                        'color_alpha' => 'false',
        ),
        'content' => array(
                        'type' => 'content',
                        'mode' => 'content',
                        'content' => '',
                        'icon' => 'false',
                        'style' => 'normal',
        ),
        'date' => array(
                        'type' => 'date',
                        'placeholder' => 'content',
                        'content' => '',
        ),
        'date' => array(
                        'type' => 'date',
                        'placeholder' => 'content',
                        'content' => '',
        ),
        'dimensions' => array(
                        'type' => 'dimensions',
                        'mode' => array(
                                  'width' => false,
                                  'height' => false 
                                ),
                        'default' => '',
                        'width' => 'true',
                        'height' => 'true',
                        'units' => 'px',
                        'units_extended' => 'false',
                        'select2' => '',
        ),
        'divide' => array(
                        'type' => 'divide',
        ),
        'editor' => array(
                        'type' => 'editor',
                        'default' => 'editor',
                        'args' => 'editor',
        ),
        'gallery' => array(
                        'type' => 'gallery',
        ),
        'image_select' => array(
                        'type' => 'image_select',
                        'output' => '',
                        'mode' => 'background-image',
                        'options' => '',
                        'width' => '',
                        'height' => '',
                        'tiles' => 'false',
                        'presets' => 'false',
        ),
        'info' => array(
            'type' => 'info',
            'style' => 'normal',
            'notice' => 'true',
            'color' => '',
            'icon' => '',
            'indent' => 'false',
        ),
        'link_color' => array(
            'type' => 'link_color',
            'regular' => 'true',
            'hover' => 'true',
            'visited' => 'true',
            'active' => 'true',
            'color_alpha' => 'false',
        ),
        'media' => array(
            'type' => 'link_color',
            'width' => '',
            'height' => '',
            'url' => 'true',
            'alt' => '',
            'preview' => 'true',
            'preview_size' => 'thumbnail',
            'placeholder' => 'No media selected',
            'readonly' => 'true',
            'mode' => 'image',
            'class' => '',
            'library_filter' => '',
            'filter' => '',
        ),
        'multi_text' => array(
            'type' => 'multi_text',
            'add_text' => 'Add More',
            'show_empty' => 'true',
        ),
        'palette' => array(
            'type' => 'palette',
            'palettes' => '',
        ),
        'password' => array(
            'type' => 'password',
            'default' => '',
            'placeholder' => array(
                'username'   => __( 'Username' ),
                'password'   => __( 'Password' )
            ),
            'username' => 'true',
        ),
        'radio' => array(
            'type' => 'radio',
            'options' => '',
            'data' => '',
        ),
        'raw' => array(
            'type' => 'raw',
            'full_width' => 'true',
            'markdown' => 'false',
            'content' => '',
            'content_path' => '',
        ),
        'section' => array(
            'type' => 'section',
            'indent' => 'true',
        ),
        'select_image' => array(
            'type' => 'select_image',
            'options' => '',
            'default' => '',
            'placeholder' => 'Select an item',
        ),
        'select' => array(
            'type' => 'select',
            'options' => '',
            'width' => '40%',
            'multi' => 'false ',
            'placeholder' => '',
            'sortable' => 'false',
            'select2' => '',
            'ajax' => 'false',
            'min-input-length' => '1',
        ),
        'slider' => array(
            'type' => 'slider',
            'min' => '0',
            'max' => '1',
            'step' => '1',
            'handles' => '1',
            'display_value' => 'text',
            'resolution' => '1',
            'float_mark' => '(decimal)',
            'select2' => '',
        ),
        'slides' => array(
            'type' => 'slides',
            'placeholder' => 'slides',
            'show' => 'slides',
        ),
        'sortable' => array(
            'type' => 'sortable',
            'options' => '',
            'label' => 'false',
            'mode' => 'text',
        ),
        'sorter' => array(
            'type' => 'sorter',
            'options' => '',
        ),
        'spacing' => array(
            'type' => 'spacing',
            'units' => '',
            'units_extended' => 'false',
            'display_units' => 'true',
            'top' => 'true',
            'bottom' => 'true',
            'left' => 'true',
            'right' => 'true',
            'all' => 'false',
            'mode' => 'padding',
            'select2' => '',
        ),
        'spinner' => array(
            'type' => 'spinner',
            'min' => '0',
            'max' => '1',
            'step' => '1',
        ),
        'switch' => array(
            'type' => 'switch',
            'on' => 'on',
            'off' => 'off',
        ),
        'text' => array(
            'type' => 'text',
            'placeholder' => '',
            'autocomplete' => '',
            'readonly' => '',
        ),
        'textarea' => array(
            'type' => 'textarea',
            'rows' => '6',
            'autocomplete' => 'false',
            'readonly' => 'false',
        ),
        'typography' => array(
            'type' => 'typography',
            'default' => '',
            'units' => 'px',
            'google' => 'true',
            'fonts' => '',
            'weights' => '',
            'font-backup' => 'false',
            'font-style' => 'true',
            'font-weight' => 'true',
            'font-size' => 'true',
            'font-size-unit' => 'true',
            'font-family' => 'true',
            'subsets' => 'true',
            'line-height' => 'true',
            'line-size-unit' => '',
            'word-spacing' => 'false',
            'word-spcaing-unit' => '',
            'letter-spacing' => 'false',
            'letter-spacing-unit' => '',
            'text-align' => 'true',
            'text-transform' => 'false',
            'color' => 'true',
            'preview' => '',
            'all_styles' => 'false',
            'select2' => '',
            'font_family_clear' => 'true',
            'margin-top' => 'false',
            'margin-top-unit' => '',
            'margin-bottom' => 'false',
            'margin-bottom-unit' => '',
            'text-shadow' => 'false',
            'allow_empty_line_height' => 'false',
            'color_alpha' => '',
        ),
    ),
];
