<?php

namespace Modules\SolarMitra\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $states = DB::table('states')->pluck('id', 'name');

        $cities = [
            // Rajasthan - All Major Cities
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jaipur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jodhpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kota', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bikaner', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhiwadi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Udaipur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ajmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhilwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Alwar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sikar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bharatpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pali', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sri Ganganagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Beawar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Baran', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Dholpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Tonk', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kishangarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Hanumangarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Banswara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Dungarpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pratapgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chittorgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nagaur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rajsamand', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sawai Madhopur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Dausa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jhunjhunu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Churu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jalore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sirohi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Barmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jaisalmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Karauli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jhalawar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bundi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mount Abu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pushkar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ranthambore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mount Abu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Rajasthan - District Headquarters & Important Towns
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Behror', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Tijara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Khairthal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kushalgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mangrol', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Antah', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chhabra', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Balotra', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kaman', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Deeg', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nadbai', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kumher', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhusawar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Weir', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bayana', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Asind', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Gulabpura', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Shahpura', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Gangapur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jahazpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mandalgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Deshnoke', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nokha', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Dungargarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nainwa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Indragarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Lakheri', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Keshoraipatan', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kaprain', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Begun', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rawatbhata', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kapasan', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nimbahera', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bari Sadri', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Taranagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rajgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sardarshahar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ratannagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ratangarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rajaldesar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bidasar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chhapar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sujangarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bandikui', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Lalsot', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bari', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rajakhera', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sagwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kesrisinghpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Karanpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sadulshahar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Gajsinghpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Padampur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Raisinghnagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Anupgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Vijainagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Suratgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sangaria', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pilibanga', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rawatsar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nohar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhadra', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kotputli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Viratnagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chomu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kishangarh Renwal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sambhar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Phulera', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jobner', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bagru', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chaksu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pokaran', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhinmal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sanchore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jhalrapatan', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Aklera', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhawani Mandi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pirawa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bissau', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mandawa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Baggar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pilani', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Vidyavihar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Surajgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chirawa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Khetri', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mukandgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nawalgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Udaipurwati', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Phalodi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pipar City', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bilara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Todabhim', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Hindaun', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kaithoon', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ramganj Mandi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sangod', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ladnu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Didwana', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mundwa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kuchera', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Merta City', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Parbatsar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Makrana', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kuchaman City', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nawa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jaitaran', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sojat', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rani', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sadri', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Takhatgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sumerpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Falna', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bali', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chhoti Sadri', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Deogarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Amet', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nathdwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Gangapur City', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ramgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Fatehpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Lachhmangarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Losal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Khandela', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sri Madhopur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Reengus', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Neem-Ka-Thana', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sheoganj', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pindwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Abu Road', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Malpura', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Niwai', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Todaraisingh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Deoli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Uniara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Fatehnagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhinder', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kanor', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Salumbar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mavli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rashmi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Garhi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Unnamed', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sursagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sanganer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Manoharpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chhoti Sadri', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bassai', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kesuli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Indergarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sujangarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rajaldesar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sidhmukh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhadra', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kolayat', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Lunkaransar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chhatargarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sardarshahar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rajgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Taranagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sri Dungargarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nokha', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kolayat', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bikaner', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Desnok', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Lunkaransar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chhatargarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Napasar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kolayat', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Palana', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mokalsar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Barmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Balotra', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sheo', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Baytoo', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pachpadra', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sindhar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jaisalmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pokaran', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Phalodi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Barmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jodhpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Luni', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bawal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Khejarla', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhopalgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Balesar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Shergarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jodhpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Piparcity', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bilara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sursagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sangariya', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kapurdi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Barmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jalore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhinmal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sanchore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Raniwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Aahore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jaswantpura', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chitalda', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jalore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sirohi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Mount Abu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Abu Road', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pindwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sheoganj', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Reodar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sirohi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Udaipur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nathdwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kankroli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Dungarpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Banswara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pratapgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Chittorgarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kota', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jhalawar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Baran', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bundi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Tonk', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ajmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Nagaur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jaipur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Dausa', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Alwar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bharatpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Dholpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Karauli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sawai Madhopur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Rajsamand', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Pali', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jodhpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bikaner', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Churu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jhunjhunu', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sikar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Hanumangarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Sri Ganganagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jaipur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Jodhpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Udaipur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Kota', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Ajmer', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Bhilwara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Rajasthan'] ?? 1, 'country_id' => 1, 'name' => 'Alwar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Maharashtra
            ['state_id' => $states['Maharashtra'] ?? 2, 'country_id' => 1, 'name' => 'Mumbai', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Maharashtra'] ?? 2, 'country_id' => 1, 'name' => 'Pune', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Maharashtra'] ?? 2, 'country_id' => 1, 'name' => 'Nagpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Maharashtra'] ?? 2, 'country_id' => 1, 'name' => 'Nashik', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Maharashtra'] ?? 2, 'country_id' => 1, 'name' => 'Thane', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Gujarat
            ['state_id' => $states['Gujarat'] ?? 3, 'country_id' => 1, 'name' => 'Ahmedabad', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Gujarat'] ?? 3, 'country_id' => 1, 'name' => 'Surat', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Gujarat'] ?? 3, 'country_id' => 1, 'name' => 'Vadodara', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Gujarat'] ?? 3, 'country_id' => 1, 'name' => 'Rajkot', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Gujarat'] ?? 3, 'country_id' => 1, 'name' => 'Gandhinagar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Karnataka
            ['state_id' => $states['Karnataka'] ?? 4, 'country_id' => 1, 'name' => 'Bengaluru', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Karnataka'] ?? 4, 'country_id' => 1, 'name' => 'Mysuru', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Karnataka'] ?? 4, 'country_id' => 1, 'name' => 'Mangaluru', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Karnataka'] ?? 4, 'country_id' => 1, 'name' => 'Hubli-Dharwad', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Tamil Nadu
            ['state_id' => $states['Tamil Nadu'] ?? 5, 'country_id' => 1, 'name' => 'Chennai', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Tamil Nadu'] ?? 5, 'country_id' => 1, 'name' => 'Coimbatore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Tamil Nadu'] ?? 5, 'country_id' => 1, 'name' => 'Madurai', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Tamil Nadu'] ?? 5, 'country_id' => 1, 'name' => 'Tiruchirappalli', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Uttar Pradesh
            ['state_id' => $states['Uttar Pradesh'] ?? 6, 'country_id' => 1, 'name' => 'Lucknow', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Uttar Pradesh'] ?? 6, 'country_id' => 1, 'name' => 'Noida', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Uttar Pradesh'] ?? 6, 'country_id' => 1, 'name' => 'Ghaziabad', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Uttar Pradesh'] ?? 6, 'country_id' => 1, 'name' => 'Agra', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Uttar Pradesh'] ?? 6, 'country_id' => 1, 'name' => 'Varanasi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Madhya Pradesh
            ['state_id' => $states['Madhya Pradesh'] ?? 7, 'country_id' => 1, 'name' => 'Bhopal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Madhya Pradesh'] ?? 7, 'country_id' => 1, 'name' => 'Indore', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Madhya Pradesh'] ?? 7, 'country_id' => 1, 'name' => 'Gwalior', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Madhya Pradesh'] ?? 7, 'country_id' => 1, 'name' => 'Jabalpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // West Bengal
            ['state_id' => $states['West Bengal'] ?? 8, 'country_id' => 1, 'name' => 'Kolkata', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['West Bengal'] ?? 8, 'country_id' => 1, 'name' => 'Howrah', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['West Bengal'] ?? 8, 'country_id' => 1, 'name' => 'Durgapur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Telangana
            ['state_id' => $states['Telangana'] ?? 9, 'country_id' => 1, 'name' => 'Hyderabad', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Telangana'] ?? 9, 'country_id' => 1, 'name' => 'Warangal', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Delhi
            ['state_id' => $states['Delhi'] ?? 10, 'country_id' => 1, 'name' => 'New Delhi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Delhi'] ?? 10, 'country_id' => 1, 'name' => 'Delhi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Punjab
            ['state_id' => $states['Punjab'] ?? 11, 'country_id' => 1, 'name' => 'Chandigarh', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Punjab'] ?? 11, 'country_id' => 1, 'name' => 'Ludhiana', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Punjab'] ?? 11, 'country_id' => 1, 'name' => 'Amritsar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Haryana
            ['state_id' => $states['Haryana'] ?? 12, 'country_id' => 1, 'name' => 'Gurugram', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Haryana'] ?? 12, 'country_id' => 1, 'name' => 'Faridabad', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Bihar
            ['state_id' => $states['Bihar'] ?? 13, 'country_id' => 1, 'name' => 'Patna', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Bihar'] ?? 13, 'country_id' => 1, 'name' => 'Gaya', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Odisha
            ['state_id' => $states['Odisha'] ?? 14, 'country_id' => 1, 'name' => 'Bhubaneswar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Odisha'] ?? 14, 'country_id' => 1, 'name' => 'Cuttack', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Kerala
            ['state_id' => $states['Kerala'] ?? 15, 'country_id' => 1, 'name' => 'Thiruvananthapuram', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Kerala'] ?? 15, 'country_id' => 1, 'name' => 'Kochi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Kerala'] ?? 15, 'country_id' => 1, 'name' => 'Kozhikode', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Assam
            ['state_id' => $states['Assam'] ?? 16, 'country_id' => 1, 'name' => 'Guwahati', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Assam'] ?? 16, 'country_id' => 1, 'name' => 'Dispur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Jharkhand
            ['state_id' => $states['Jharkhand'] ?? 17, 'country_id' => 1, 'name' => 'Ranchi', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Jharkhand'] ?? 17, 'country_id' => 1, 'name' => 'Jamshedpur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Chhattisgarh
            ['state_id' => $states['Chhattisgarh'] ?? 18, 'country_id' => 1, 'name' => 'Raipur', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Goa
            ['state_id' => $states['Goa'] ?? 19, 'country_id' => 1, 'name' => 'Panaji', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Goa'] ?? 19, 'country_id' => 1, 'name' => 'Margao', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Uttarakhand
            ['state_id' => $states['Uttarakhand'] ?? 20, 'country_id' => 1, 'name' => 'Dehradun', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Uttarakhand'] ?? 20, 'country_id' => 1, 'name' => 'Haridwar', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            // Himachal Pradesh
            ['state_id' => $states['Himachal Pradesh'] ?? 21, 'country_id' => 1, 'name' => 'Shimla', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
            ['state_id' => $states['Himachal Pradesh'] ?? 21, 'country_id' => 1, 'name' => 'Manali', 'status' => true, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('cities')->insert($cities);
    }
}
