<?php

namespace Modules\SolarMitra\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConfigMasterSeeder extends Seeder
{
    public function run(): void
    {
        $configs = [

            // =====================================================
            // Global (16 records)
            // =====================================================
            [
                'module_code' => 'global',
                'field_key' => 'date_format',
                'display_title' => 'Date Format',
                'description' => 'Format used to display dates in the system.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "F j, Y": "March 6, 2026",
  "Y-m-d": "2026-03-06",
  "d-m-Y": "06-03-2026",
  "d/m/Y": "06/03/2026",
  "m/d/Y": "03/06/2026",
  "M d, Y": "Mar 06, 2026",
  "d M Y": "06 Mar 2026"
}',
                'field_value' => 'Y-m-d',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'time_format',
                'display_title' => 'Time Format',
                'description' => 'Format used to display time.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "g:i A": "2:30 PM",
  "h:i A": "02:30 PM",
  "H:i:s": "14:30:00",
  "H:i": "14:30"
}',
                'field_value' => 'H:i:s',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 2,
                'help_text' => 'Set the Time Format here',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'timezone',
                'display_title' => 'TimeZone',
                'description' => 'Default timezone for system operations.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "UTC": "UTC",
  "Asia/Kolkata": "India Standard Time (IST)",
  "America/New_York": "Eastern Time (US)",
  "Europe/London": "Greenwich Mean Time (GMT)",
  "Asia/Dubai": "Gulf Standard Time",
  "Asia/Singapore": "Singapore Standard Time",
  "Australia/Sydney": "Australian Eastern Time"
}',
                'field_value' => 'Asia/Kolkata',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 3,
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'currency_code',
                'display_title' => 'Currency Code',
                'description' => 'Currency code used for financial transactions (e.g., INR, USD).',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "INR": "Indian Rupee",
  "USD": "US Dollar",
  "EUR": "Euro",
  "GBP": "British Pound",
  "AED": "UAE Dirham",
  "JPY": "Japanese Yen",
  "SGD": "Singapore Dollar",
  "AUD": "Australian Dollar"
}',
                'field_value' => 'USD',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'currency_symbol',
                'display_title' => 'Currency Symbol',
                'description' => 'Symbol used to represent currency (₹, $, etc.).',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "₹": "₹ (Indian Rupee)",
  "$": "$ (Dollar)",
  "€": "€ (Euro)",
  "£": "£ (Pound)",
  "¥": "¥ (Yen)",
  "د.إ": "د.إ (Dirham)",
  "S$": "S$ (Singapore Dollar)",
  "A$": "A$ (Australian Dollar)"
}',
                'field_value' => '$',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'number_format',
                'display_title' => 'Number Format',
                'description' => 'Format for displaying numbers (Indian or international style).',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "indian": "Indian Format (1,00,000.00)",
  "international": "International Format (100,000.00)",
  "plain": "Plain Number (100000.00)",
  "space_separator": "Space Separator (100 000.00)"
}',
                'field_value' => 'international',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'decimal_precision',
                'display_title' => 'Decimal Precision',
                'description' => 'Number of decimal places for numeric values.',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'select',
                'options_json' => '{
  "0": "0 Decimal Places (100)",
  "1": "1 Decimal Place (100.0)",
  "2": "2 Decimal Places (100.00)",
  "3": "3 Decimal Places (100.000)",
  "4": "4 Decimal Places (100.0000)",
  "5": "5 Decimal Places (100.00000)",
  "6": "6 Decimal Places (100.000000)"
}',
                'field_value' => 2,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'language',
                'display_title' => 'Language',
                'description' => 'Default language used in the application.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "en": "English",
  "hi": "Hindi",
  "gu": "Gujarati",
  "mr": "Marathi",
  "ta": "Tamil",
  "te": "Telugu",
  "bn": "Bengali",
  "fr": "French",
  "de": "German",
  "es": "Spanish"
}',
                'field_value' => 'en',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'financial_year_start',
                'display_title' => 'Financial Year Start',
                'description' => 'Month when the financial year begins.(month and year)',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'working_days',
                'display_title' => 'Working Days',
                'description' => 'Days considered as working days in the system.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => '5',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'working_hours',
                'display_title' => 'Working Hours',
                'description' => 'Standard daily working hours.',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'text',
                'field_value' => '8',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'service_area',
                'display_title' => 'Service Area (Location)',
                'description' => 'Geographic area where services are provided.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'auto_number_reset',
                'display_title' => 'Auto Number Reset',
                'description' => 'In a Solar Business Management System, you will auto-generate numbers for Invoice, Quotation or etc.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'gi_price_per_kg',
                'display_title' => 'GI Price Per KG',
                'description' => 'Cost per kilogram of galvanized iron (GI) for solar structure.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 67,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'ms_price_per_kg',
                'display_title' => 'MS Price Per KG',
                'description' => 'Cost per kilogram of mild steel (MS) for solar structure.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 67,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'global',
                'field_key' => 'hot_dip_price_per_kg',
                'display_title' => 'Hot Dip Price Per KG',
                'description' => 'Cost per kilogram for applying hot-dip galvanization to mild steel to protect against corrosion.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 67,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // User (6 records)
            // =====================================================
            [
                'module_code' => 'user',
                'field_key' => 'emp_code_prefix',
                'display_title' => 'Emp Code Prefix',
                'description' => 'Prefix added before employee codes.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'user',
                'field_key' => 'emp_code_suffix',
                'display_title' => 'Emp Code Suffix',
                'description' => 'Suffix added after employee codes.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'user',
                'field_key' => 'emp_start_number',
                'display_title' => 'Emp Start Number',
                'description' => 'Starting number for employee code generation.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'user',
                'field_key' => 'emp_reset_rule',
                'display_title' => 'Emp Reset Rule',
                'description' => 'Rule defining when employee numbering resets.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'user',
                'field_key' => 'role_based_access',
                'display_title' => 'Role Based Access',
                'description' => 'Enables role-based access control for users.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'user',
                'field_key' => 'approval_required',
                'display_title' => 'Approval Required',
                'description' => 'Determines if approval is required for actions.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // Invoice (8 records)
            // =====================================================
            [
                'module_code' => 'invoice',
                'field_key' => 'invoice_prefix',
                'display_title' => 'Invoice Prefix',
                'description' => 'Prefix added before invoice numbers.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 17,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'invoice',
                'field_key' => 'invoice_suffix',
                'display_title' => 'Invoice Suffix',
                'description' => 'Suffix added after invoice numbers.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 18,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'invoice',
                'field_key' => 'invoice_start_number',
                'display_title' => 'Invoice Start Number',
                'description' => 'Starting number for invoice generation.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 19,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'invoice',
                'field_key' => 'invoice_reset_rule',
                'display_title' => 'Invoice Reset Rule',
                'description' => 'Rule for resetting invoice numbering.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'invoice',
                'field_key' => 'allow_partial_payment',
                'display_title' => 'Allow Partial Payment',
                'description' => 'Allows customers to make partial payments.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 21,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'invoice',
                'field_key' => 'due_days',
                'display_title' => 'Payment Due Days',
                'description' => 'Number of days allowed before payment becomes due.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 22,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'invoice',
                'field_key' => 'late_fee_enabled',
                'display_title' => 'Late Fee Enabled',
                'description' => 'Enables late fee for overdue payments.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 23,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'invoice',
                'field_key' => 'show_invoice_round_of',
                'display_title' => 'Show Invoice Round Of',
                'description' => 'Show Invoice Round Of Block',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 88,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // Solar (11 records)
            // =====================================================
            [
                'module_code' => 'solar',
                'field_key' => 'load_unit',
                'display_title' => 'Load Unit',
                'description' => 'Unit used for system load measurement (e.g., kW).',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => 'kW',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'default_panel_type',
                'display_title' => 'Default Panel Type',
                'description' => 'Default type of solar panel used in projects.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'select',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 25,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'default_inverter_brand',
                'display_title' => 'Default Inverter Brand',
                'description' => 'Default inverter brand selected for installations.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'select',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 26,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'subsidy_applicable',
                'display_title' => 'Subsidy Applicable',
                'description' => 'Indicates if subsidy applies to installations.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 27,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'subsidy_percentage',
                'display_title' => 'Subsidy Percentage',
                'description' => 'Percentage of subsidy applied to project cost.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 28,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'net_metering_required',
                'display_title' => 'Net Metering Required',
                'description' => 'Specifies if net metering is mandatory.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 29,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'site_survey_required',
                'display_title' => 'Site Survey Required',
                'description' => 'Determines if site survey is required before installation.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'minimum_load',
                'display_title' => 'Minimum Load',
                'description' => 'Minimum system load allowed for projects.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 31,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'shadow_analysis_required',
                'display_title' => 'Shadow Analysis Required',
                'description' => 'Indicates if shadow analysis is required.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'switch',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 32,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'rooftop_type_options',
                'display_title' => 'Rooftop Type Options',
                'description' => 'Available rooftop types for installation selection.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "rcc": "RCC Roof",
  "tin_shed": "Tin Shed",
  "tile": "Tile Roof",
  "asbestos": "Asbestos Roof",
  "metal_sheet": "Metal Sheet Roof",
  "ground": "Ground Mount"
}',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 33,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar',
                'field_key' => 'installation_phases',
                'display_title' => 'Installation Phases',
                'description' => 'Stages involved in the installation process.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 34,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // Solar Project (19 records)
            // =====================================================
            [
                'module_code' => 'solar_project',
                'field_key' => 'price_per_kw',
                'display_title' => 'Price Per Kw',
                'description' => 'Base price charged per kilowatt of system capacity.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => '30',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 35,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'area_required_per_kw',
                'display_title' => 'Area Required Per KW',
                'description' => 'Roof area required per kilowatt installation.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => '30',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 35,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'installation_days',
                'display_title' => 'Installation Days',
                'description' => 'Estimated days required to complete installation.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => '30',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 36,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'boq_auto_generate',
                'display_title' => 'BOQ Auto Generate',
                'description' => 'Automatically generate bill of quantities for projects.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 37,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'material_auto_deduct',
                'display_title' => 'Material Auto Deduct',
                'description' => 'Automatically deduct materials from inventory.',
                'config_group' => 'Solar',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '0',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 38,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'adani_cost_per_watt',
                'display_title' => 'Adani Cost Per Watt',
                'description' => 'Cost Per Watt for Adani Panels .',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'text',
                'field_value' => '45',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 69,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'tata_cost_per_watt',
                'display_title' => 'Tata Cost Per Watt',
                'description' => 'Cost Per Watt for Tata Panels .',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'text',
                'field_value' => '39',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => true,
                'display_order' => 70,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'waaree_cost_per_watt',
                'display_title' => 'Waaree Cost Per Watt',
                'description' => 'Cost Per Watt for Waaree Panels .',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'text',
                'field_value' => '42',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 71,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'solar_installation_margin_unit',
                'display_title' => 'Solar Installation Margin Unit',
                'description' => 'Solar Installation Margin Unit',
                'config_group' => 'Default Margin Setting',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "%": "%",
  "Fix": "Fix"
}',
                'field_value' => '%',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 72,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'solar_installation_margin_value',
                'display_title' => 'Solar Installation General Margin Value',
                'description' => 'Default If Advance price is not Set',
                'config_group' => 'Default Margin Setting',
                'value_type' => 'number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 73,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'central_govt_subsidy_amount',
                'display_title' => 'Central Govt Subsidy Amount',
                'description' => 'Central Govt Subsidy Amount',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'text',
                'field_value' => '78,000',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 74,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'central_govt_subsidy_content',
                'display_title' => 'Central Govt Subsidy Content',
                'description' => 'Central Govt Subsidy Content',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'textarea',
                'field_value' => 'Central Government',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 75,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'state_govt_subsidy_amount',
                'display_title' => 'State Govt Subsidy Amount',
                'description' => 'State Govt Subsidy Amount',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'text',
                'field_value' => '17,000',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 76,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'state_govt_subsidy_content',
                'display_title' => 'State Govt Subsidy Content',
                'description' => 'State Govt Subsidy Content',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => 'State Government (When applied)',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 77,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'solar_installation_margin_for_1kw_3kw',
                'display_title' => 'Margin Amount for 1Kw - 3Kw',
                'description' => 'Solar Installation Margin Amount for 1Kw - 3Kw',
                'config_group' => 'Pricing',
                'value_type' => 'number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 78,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'solar_installation_margin_for_4kw_7kw',
                'display_title' => 'Margin Amount for 4Kw - 7Kw',
                'description' => 'Solar Installation Margin Amount for 4Kw - 7Kw',
                'config_group' => 'Pricing',
                'value_type' => 'number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 79,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'solar_installation_margin_for_8kw_15kw',
                'display_title' => 'Margin Amount for 8Kw - 15Kw',
                'description' => 'Solar Installation Margin Amount for 8Kw - 15Kw',
                'config_group' => 'Pricing',
                'value_type' => 'number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 80,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'solar_project',
                'field_key' => 'solar_installation_margin_for_16kw_plus',
                'display_title' => 'Margin Amount for 16Kw+',
                'description' => 'Solar Installation Margin Amount for 16Kw+',
                'config_group' => 'Pricing',
                'value_type' => 'number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 81,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // Quotation (17 records)
            // =====================================================
            [
                'module_code' => 'quotation',
                'field_key' => 'enable_item_level_pricing',
                'display_title' => 'Enable Item Level Pricing',
                'description' => 'Allows pricing to be set per item in quotations.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 39,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'allow_manual_price_override',
                'display_title' => 'Allow Manual Price Override',
                'description' => 'Allows users to manually override item prices.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 40,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'show_margin_to_sales',
                'display_title' => 'Show Margin To Sales',
                'description' => 'Displays profit margin to sales users.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 41,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'allow_discount',
                'display_title' => 'Allow Discount',
                'description' => 'Allows discounts to be applied to quotations.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 42,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'discount_type',
                'display_title' => 'Discount Type',
                'description' => 'Type of discount applied (percentage or fixed).',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "%": "%",
  "fixed": "Fixed"
}',
                'field_value' => '%',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 43,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'max_discount_limit',
                'display_title' => 'Max Discount Limit',
                'description' => 'Maximum discount allowed without approval.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => '100',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 44,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'discount_approval_required',
                'display_title' => 'Discount Approval Required',
                'description' => 'Requires approval for discounts above limit.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '0',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 45,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'quotation_number_format',
                'display_title' => 'Quotation Number Format',
                'description' => 'Format used for generating quotation numbers.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 49,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'reset_number_yearly',
                'display_title' => 'Reset Number Yearly',
                'description' => 'Resets quotation numbering every year.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '0',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 50,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'default_validity_days',
                'display_title' => 'Default Validity Days',
                'description' => 'Default validity period for quotations.',
                'config_group' => 'Common',
                'field_type' => 'text',
                'field_value' => '7',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 51,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'auto_expire_quotation',
                'display_title' => 'Auto Expire Quotation',
                'description' => 'Automatically expire quotations after validity.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '0',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 52,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'quotaion_approval_required',
                'display_title' => 'Quotation Approval Required',
                'description' => 'Indicates if quotation approval is needed.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '0',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 53,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'approval_trigger_amount',
                'display_title' => 'Approval Trigger Amount',
                'description' => 'Amount above which approval is required.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 54,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'quotation_prefix',
                'display_title' => 'Quotation Prefix',
                'description' => 'Prefix added before Quotation numbers.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 63,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'quotation_suffix',
                'display_title' => 'Quotation Suffix',
                'description' => 'Suffix added after Quotation numbers.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 64,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'quotation_start_number',
                'display_title' => 'Quotation Start Number',
                'description' => 'Starting number for Quotation generation.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 65,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'quotation_reset_rule',
                'display_title' => 'Quotation Number Reset Rule',
                'description' => 'Rule for resetting Quotation numbering.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 66,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'quotation',
                'field_key' => 'quotation_limit_per_client',
                'display_title' => 'Quotation Limit Per Client',
                'description' => 'Quotation Limit Per Client',
                'config_group' => 'Common',
                'value_type' => 'number',
                'field_type' => 'text',
                'field_value' => '3',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 87,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // Tax (4 records)
            // =====================================================
            [
                'module_code' => 'tax',
                'field_key' => 'default_tax_type',
                'display_title' => 'Default Tax Type',
                'description' => 'Default tax type applied to transactions.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "gst": "GST (Goods and Services Tax)",
  "vat": "VAT (Value Added Tax)",
  "none": "No Tax"
}',
                'field_value' => 'gst',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 46,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'tax',
                'field_key' => 'gst_mode',
                'display_title' => 'GST Mode',
                'description' => 'GST calculation mode (intra/inter state).',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'select',
                'options_json' => '{
  "intra_state": "Intra State",
  "inter_state": "Inter State",
  "auto": "Auto"
}',
                'field_value' => 'auto',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 47,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'tax',
                'field_key' => 'gst_inclusive_pricing',
                'display_title' => 'GST Inclusive Pricing',
                'description' => 'Indicates if prices include GST.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 48,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'tax',
                'field_key' => 'show_tax_breakup',
                'display_title' => 'Show Tax Breakup',
                'description' => 'Shows detailed tax breakdown in quotation.',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 62,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // Documents (7 records)
            // =====================================================
            [
                'module_code' => 'documents',
                'field_key' => 'show_company_bank_details',
                'display_title' => 'Show Company Bank Details',
                'description' => 'Displays company bank details on quotations.',
                'config_group' => 'quotation_layout',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 55,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'documents',
                'field_key' => 'show_terms_and_conditions',
                'display_title' => 'Show Terms And Conditions',
                'description' => 'Shows terms and conditions in quotations.',
                'config_group' => 'quotation_layout',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 56,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'documents',
                'field_key' => 'quotation_template_type',
                'display_title' => 'Quotation Template Type',
                'description' => 'Template layout used for quotations.',
                'config_group' => 'quotation_layout',
                'value_type' => 'string',
                'field_type' => 'select',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 57,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'documents',
                'field_key' => 'show_system_generation_estimate',
                'display_title' => 'Show System Generation Estimate',
                'description' => 'Displays estimated system power generation.',
                'config_group' => 'quotation_layout',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 58,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'documents',
                'field_key' => 'show_subsidy_calculation',
                'display_title' => 'Show Subsidy Calculation',
                'description' => 'Shows subsidy calculation in quotation.',
                'config_group' => 'quotation_layout',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 59,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'documents',
                'field_key' => 'subsidy_auto_calculate',
                'display_title' => 'Subsidy Auto Calculate',
                'description' => 'Automatically calculates subsidy amount.',
                'config_group' => 'quotation_layout',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => '1',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 60,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'module_code' => 'documents',
                'field_key' => 'show_item_description',
                'display_title' => 'Show Item Description',
                'description' => 'Displays detailed item descriptions.',
                'config_group' => 'quotation_layout',
                'value_type' => 'string',
                'field_type' => 'switch',
                'field_value' => 1,
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 61,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================================
            // Lead (1 record)
            // =====================================================
            [
                'module_code' => 'lead',
                'field_key' => 'followup_alert_before_days',
                'display_title' => 'Follow Up Alert Before Days',
                'description' => 'Follow Up Alert Before Days',
                'config_group' => 'Common',
                'value_type' => 'string',
                'field_type' => 'text',
                'field_value' => '3',
                'is_required' => false,
                'is_readonly' => false,
                'is_hidden' => false,
                'is_multiple' => false,
                'display_order' => 68,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Every row in a multi-row insert() must have the exact same set of
        // keys (Laravel derives the column list from the first row and then
        // maps subsequent rows positionally). Some rows above are missing
        // keys like 'field_value' / 'options_json' / 'help_text' — fill in
        // every column from the migration so all rows line up identically.
        $defaults = [
            'module_code' => null,
            'field_key' => null,
            'display_title' => null,
            'description' => null,
            'industry_code' => null,
            'config_group' => null,
            'value_type' => 'string',
            'field_type' => 'text',
            'options_json' => null,
            'field_value' => null,
            'validation_rules_json' => null,
            'is_required' => false,
            'is_readonly' => false,
            'is_hidden' => false,
            'is_multiple' => false,
            'min_value' => null,
            'max_value' => null,
            'step_value' => null,
            'regex_pattern' => null,
            'depends_on_key' => null,
            'depends_on_value' => null,
            'display_order' => 0,
            'help_text' => null,
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ];

        $configs = array_map(function ($row) use ($defaults) {
            // array_merge($defaults, $row) guarantees every row ends up
            // with the exact same keys, in the exact same order — any
            // key present in $row overrides the default, any key absent
            // from $row falls back to the default instead of being missing.
            return array_merge($defaults, $row);
        }, $configs);

        DB::table('config_master')->insert($configs);
    }
}
