<?php

namespace Modules\SolarMitra\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'title' => 'Structure',
                'slug' => 'structure',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 1,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Panel',
                'slug' => 'panel',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => true,
                'order' => 2,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Inverter',
                'slug' => 'inverter',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => true,
                'order' => 3,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Battery',
                'slug' => 'battery',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => true,
                'order' => 4,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wire',
                'slug' => 'wire',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 5,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ACDB',
                'slug' => 'acdb',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => true,
                'order' => 6,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DCDB',
                'slug' => 'dcdb',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => true,
                'order' => 7,
                'gst' => null,
                'description' => 'DC Distribution Box',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Solar Kit',
                'slug' => 'solar-kit',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 8,
                'gst' => null,
                'description' => 'Combined Items in One Kit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'MC4 Connector',
                'slug' => 'mc4-connector',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 9,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Workmanship (Installation)',
                'slug' => 'workmanship-installation',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 10,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Transport',
                'slug' => 'transport',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 11,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Solar meter',
                'slug' => 'solar-meter',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 12,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Net  meter',
                'slug' => 'net-meter',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 13,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Other',
                'slug' => 'other',
                'display_on_invoice' => true,
                'calculate_in_invoice' => true,
                'include_in_solar_kit' => false,
                'order' => 14,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Condute pipe',
                'slug' => 'condute-pipe',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 15,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Earthing Rod',
                'slug' => 'earthing-rod',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 16,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Earthing Cable',
                'slug' => 'earthing-cable',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 17,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'MCB',
                'slug' => 'mcb',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 18,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DC Wire',
                'slug' => 'dc-wire',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 19,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lightning Arrester',
                'slug' => 'lightning-arrester',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 20,
                'gst' => null,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'T - Elbow',
                'slug' => 't-elbow',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 21,
                'gst' => 18.00,
                'description' => 'Elbow 25mm , Elbow 20mm, Elbow 16mm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Shaddle',
                'slug' => 'shaddle',
                'display_on_invoice' => false,
                'calculate_in_invoice' => false,
                'include_in_solar_kit' => false,
                'order' => 22,
                'gst' => 18.00,
                'description' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('material_categories')->insert($categories);
    }
}
