<?php

namespace Modules\SolarMitra\Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionSeeder extends Seeder
{
    /**
     * Permission matrix from SolarSiteMasterPermissions.xlsx.
     * Format: ['Module', 'Controller', 'action', ['Role1', 'Role2', ...]]
     *
     * Permission names are created as: SolarMitra > {Module} > {Controller}Controller > {action}
     * to match the format generated by PermissionsController::add_to_permissions().
     *
     * Level 0 role "Business" gets ALL permissions.
     * Level 1 roles (Staff, Clients, etc.) get 0 permissions.
     * Level 2 roles get permissions per the matrix below.
     */
    private array $permissionMatrix = [
        ['Business', 'Quotations', 'view_quotation', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'download_quotation', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'index', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'create', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'store', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'edit', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'show', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'update', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'destroy', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'confirm_quotation', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'convert_to_invoice', ['CEO','Sales Manager','Sales Executive','Accounts Manager','Customer Support']],
        ['Business', 'Quotations', 'get_item_by_category', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'get_brands_by_category', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'add_quotation_item', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'add_quotation_category', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'ajax_quotation_addmore_item', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'ajax_quotation_items', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'share_quotation', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'send_quotation_pdf', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Quotations', 'ajax_quotation_calculate', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Invoices', 'view_invoice', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'download_invoice', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'index', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'create', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'store', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'edit', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'update', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'destroy', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'share_invoice', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'get_contact_invoices', ['CEO','Sales Manager','Sales Executive','Service Engineer','Accounts Manager','Customer Support']],
        ['Business', 'Invoices', 'change_to_paid', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Auth', 'register', ['CEO']],
        ['Business', 'Auth', 'login', ['CEO']],
        ['Business', 'Auth', 'verification', ['CEO','Site Survey Engineer']],
        ['Business', 'Auth', 'verify_email', ['CEO']],
        ['Business', 'Auth', 'verify_mobile', ['CEO']],
        ['Business', 'Auth', 'verify_user', ['CEO']],
        ['Business', 'Auth', 'resend_otp', ['CEO']],
        ['Business', 'Auth', 'store', ['CEO']],
        ['Business', 'Auth', 'destroy', ['CEO']],
        ['Business', 'Auth', 'regenerateRecoveryCodes', ['CEO']],
        ['Business', 'Auth', 'profile', ['CEO']],
        ['Business', 'Auth', 'logout', ['CEO']],
        ['Business', 'Auth', 'update_user', ['CEO']],
        ['Business', 'Auth', 'update_password', ['CEO']],
        ['Business', 'Business', 'dashboard', ['CEO','Sales Manager','Sales Executive']],
        ['Business', 'Business', 'get_invoice_series', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Business', 'settings', ['CEO']],
        ['Business', 'Business', 'save_business', ['CEO']],
        ['Business', 'Business', 'bank_account', ['CEO']],
        ['Business', 'Business', 'bank_account_destroy', ['CEO']],
        ['Business', 'Business', 'address', ['CEO']],
        ['Business', 'Business', 'address_make_primary', ['CEO']],
        ['Business', 'Business', 'address_destroy', ['CEO']],
        ['Business', 'Projects', 'index', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'dashboard', ['CEO','Operations Manager','Sales Manager','Sales Executive','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'create', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor']],
        ['Business', 'Projects', 'store', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor']],
        ['Business', 'Projects', 'edit', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'update', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'destroy', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'assign_project', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'documents', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'verification', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'subsidy', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'structure', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'netmeter', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'handover', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'remove_document', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'remove_project_attachment', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'get_contact_projects', ['CEO','Operations Manager','Sales Manager','Sales Executive','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Customer Support']],
        ['Business', 'Projects', 'save_project_phase', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'archived_projects', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Projects', 'move_to_projects', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician']],
        ['Business', 'Transactions', 'index', ['CEO','Operations Manager','Accounts Manager']],
        ['Business', 'Transactions', 'create', ['CEO','Operations Manager','Accounts Manager']],
        ['Business', 'Transactions', 'store', ['CEO','Operations Manager','Accounts Manager']],
        ['Business', 'Transactions', 'edit', ['CEO','Operations Manager','Accounts Manager']],
        ['Business', 'Transactions', 'update', ['CEO','Operations Manager','Accounts Manager']],
        ['Business', 'Transactions', 'destroy', ['CEO','Operations Manager','Accounts Manager']],
        ['Business', 'Contacts', 'index', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'create', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'store', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'edit', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'update', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'assign_type', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'destroy', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'multi_destroy', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'assign_login', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'clients', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'staff', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'contractors', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'suppliers', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'investors', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Contacts', 'partners', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'BusinessConfigMaster', 'manage', ['CEO']],
        ['Business', 'BusinessConfigMaster', 'reset_business_configs', ['CEO']],
        ['Business', 'Materials', 'index', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'create', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'store', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'edit', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'show', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'update', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'export', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'import', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'Materials', 'get_unit_by_category', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCategories', 'list', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCategories', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCategories', 'moveup', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCategories', 'movedown', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCompanies', 'ajax_modal', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCompanies', 'index', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCompanies', 'store', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCompanies', 'update', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialCompanies', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialUnits', 'list', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'MaterialUnits', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Business', 'QuotationItems', 'index', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'QuotationItems', 'create', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'QuotationItems', 'store', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'QuotationItems', 'edit', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'QuotationItems', 'update', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'QuotationItems', 'destroy', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Business', 'Leads', 'index', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'create', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'store', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'lead_followed', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'details', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'edit', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'update', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'destroy', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'multi_destroy', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'assign_lead', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'lead_change_stage', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'lead_client_group', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'lead_source', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'lead_potential', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'export', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'import', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'client_group', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'destroy_client_group', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'sources', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'destroy_source', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'channels', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Leads', 'destroy_channel', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Campaigns', 'index', ['CEO']],
        ['Business', 'Campaigns', 'create', ['CEO']],
        ['Business', 'Campaigns', 'store', ['CEO']],
        ['Business', 'Campaigns', 'edit', ['CEO']],
        ['Business', 'Campaigns', 'update', ['CEO']],
        ['Business', 'Campaigns', 'destroy', ['CEO']],
        ['Business', 'BusinessRoles', 'index', ['CEO']],
        ['Business', 'BusinessRoles', 'dashboard', ['CEO','Sales Manager','Sales Executive']],
        ['Business', 'BusinessRoles', 'create', ['CEO']],
        ['Business', 'BusinessRoles', 'store', ['CEO']],
        ['Business', 'BusinessRoles', 'edit', ['CEO']],
        ['Business', 'BusinessRoles', 'update', ['CEO']],
        ['Business', 'BusinessRoles', 'destroy', ['CEO']],
        ['Business', 'Permissions', 'index', ['CEO']],
        ['Business', 'Permissions', 'roles_permissions', ['CEO']],
        ['Business', 'Permissions', 'user_permissions', ['CEO']],
        ['Business', 'Permissions', 'manage_user_permissions', ['CEO']],
        ['Business', 'Permissions', 'manage_role_all_permissions', ['CEO']],
        ['Business', 'Permissions', 'manage_role_permission', ['CEO']],
        ['Business', 'Permissions', 'manage_user_permission', ['CEO']],
        ['Business', 'Permissions', 'delete_user_permission', ['CEO']],
        ['Business', 'Permissions', 'manage_user_all_permission', ['CEO']],
        ['Business', 'Permissions', 'temp_permissions', ['CEO']],
        ['Business', 'Permissions', 'generate_permissions', ['CEO']],
        ['Business', 'Permissions', 'add_to_permissions', ['CEO']],
        ['Business', 'Permissions', 'permission_by_action', ['CEO']],
        ['Business', 'Permissions', 'get_users_by_role', ['CEO']],
        ['Business', 'Permissions', 'get_permission_by_user', ['CEO']],
        ['Admin', 'Businesses', 'index', ['CEO']],
        ['Admin', 'Businesses', 'create', ['CEO']],
        ['Admin', 'Businesses', 'store', ['CEO']],
        ['Admin', 'Businesses', 'edit', ['CEO']],
        ['Admin', 'Businesses', 'update', ['CEO']],
        ['Admin', 'Businesses', 'destroy', ['CEO']],
        ['Admin', 'ConfigMaster', 'index', ['CEO']],
        ['Admin', 'ConfigMaster', 'create', ['CEO']],
        ['Admin', 'ConfigMaster', 'store', ['CEO']],
        ['Admin', 'ConfigMaster', 'edit', ['CEO']],
        ['Admin', 'ConfigMaster', 'update', ['CEO']],
        ['Admin', 'ConfigMaster', 'destroy', ['CEO']],
        ['Admin', 'ConfigMaster', 'manage', ['CEO']],
        ['Admin', 'TransactionTypes', 'list', ['CEO','Operations Manager','Accounts Manager']],
        ['Admin', 'TransactionTypes', 'destroy', ['CEO','Operations Manager','Accounts Manager']],
        ['Admin', 'Projects', 'project_phases', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Admin', 'Projects', 'project_phases_view', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Admin', 'Projects', 'destory_project_phase', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager']],
        ['Admin', 'Quotations', 'get_brands_by_category', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Admin', 'Materials', 'index', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'Materials', 'create', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'Materials', 'store', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'Materials', 'edit', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'Materials', 'update', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'Materials', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'Materials', 'get_unit_by_category', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCategories', 'list', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCategories', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCategories', 'moveup', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCategories', 'movedown', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCompanies', 'ajax_modal', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCompanies', 'index', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCompanies', 'store', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCompanies', 'update', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialCompanies', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialUnits', 'list', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'MaterialUnits', 'destroy', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Admin', 'BusinessRoles', 'index', ['CEO']],
        ['Admin', 'BusinessRoles', 'create', ['CEO']],
        ['Admin', 'BusinessRoles', 'store', ['CEO']],
        ['Admin', 'BusinessRoles', 'edit', ['CEO']],
        ['Admin', 'BusinessRoles', 'update', ['CEO']],
        ['Admin', 'BusinessRoles', 'destroy', ['CEO']],
        ['Api', 'Auth', 'register_with_email', ['CEO']],
        ['Api', 'Auth', 'register_with_mobile', ['CEO']],
        ['Api', 'Auth', 'login_with_email', ['CEO']],
        ['Api', 'Auth', 'login_with_password', ['CEO']],
        ['Api', 'Auth', 'login_with_mobile', ['CEO']],
        ['Api', 'Auth', 'verify_otp', ['CEO']],
        ['Api', 'Auth', 'profile', ['CEO']],
        ['Api', 'Auth', 'logout', ['CEO']],
        ['Api', 'Dashboard', 'dashboard', ['CEO','Sales Manager','Sales Executive']],
        ['Api', 'Projects', 'list', ['CEO','Operations Manager','CRM / Lead Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'save_project', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'destroy', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'assign_staff', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'documents', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'verification', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'subsidy', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'structure', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'netmeter', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'handover', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'remove_review_video', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'remove_document', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Projects', 'remove_project_attachment', ['CEO','Operations Manager','Site Survey Engineer','Solar Design Engineer','Project Manager','Installation Supervisor','Solar Technician','Service Engineer']],
        ['Api', 'Contacts', 'list', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Api', 'Contacts', 'store', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Api', 'Contacts', 'destroy', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Api', 'Quotations', 'list', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Quotations', 'get_dropdown_list', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Quotations', 'save_quotation', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Quotations', 'destroy', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Quotations', 'status_change', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Quotations', 'item_destroy', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Quotations', 'convert_to_invoice', ['CEO','Sales Manager','Sales Executive','Accounts Manager','Customer Support']],
        ['Api', 'Quotations', 'view_quotation', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Quotations', 'download_quotation', ['CEO','Sales Manager','Sales Executive','Customer Support']],
        ['Api', 'Invoices', 'list', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Invoices', 'destroy', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Invoices', 'update', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Invoices', 'view_invoice', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Invoices', 'download_invoice', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Materials', 'list', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Api', 'Materials', 'get_category_with_company', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Api', 'Materials', 'get_companies_by_category', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Api', 'Materials', 'get_items_by_company_and_category', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Api', 'Materials', 'get_item_by_category', ['CEO','Operations Manager','Procurement Manager','Inventory Manager']],
        ['Api', 'Leads', 'index', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Api', 'Leads', 'save_multiple', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Api', 'Leads', 'lead_resources', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Api', 'Leads', 'save_lead', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Api', 'Leads', 'destroy', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Api', 'Leads', 'assign_lead', ['CEO','Sales Manager','Sales Executive','CRM / Lead Manager','Customer Support']],
        ['Business', 'Contacts', 'verify_user_direct', ['CEO','Sales Manager','Sales Executive','Service Engineer','Customer Support']],
        ['Business', 'Auth', 'check_user_exists', ['CEO']],
        ['Business', 'Auth', 'login_with_otp', ['CEO']],
        ['Business', 'Auth', 'send_login_otp', ['CEO']],
        ['Api', 'Invoices', 'store', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Invoices', 'change_to_paid', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Auth', 'update_contact_form', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Auth', 'update_contact', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Contacts', 'verify_user_modal', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Contacts', 'verify_user_field', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Permissions', 'get_role_permissions', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Channels', 'index', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Channels', 'create', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Channels', 'store', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Channels', 'edit', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Channels', 'update', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Channels', 'destroy', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Sources', 'index', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Sources', 'create', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Sources', 'store', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Sources', 'edit', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Sources', 'update', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'Sources', 'destroy', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Admin', 'AppFeedbacks', 'index', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Invoices', 'show', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Transactions', 'list', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Transactions', 'show', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Transactions', 'store', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Transactions', 'update', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Transactions', 'destroy', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Transactions', 'get_expense_head', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'Transactions', 'get_income_head', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Api', 'AppFeedbacks', 'store', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
        ['Business', 'Invoices', 'show', ['CEO','Sales Manager','Sales Executive','Accounts Manager']],
    ];

    public function run(): void
    {
        $this->command->info('RolePermissionSeeder: Starting...');

        // 1. Collect unique permission names from the matrix
        $permissionNames = [];
        foreach ($this->permissionMatrix as [$module, $controller, $action, $roles]) {
            $permissionNames[] = $this->buildPermissionName($module, $controller, $action);
        }
        $permissionNames = array_unique($permissionNames);

        $this->command->info('RolePermissionSeeder: ' . count($permissionNames) . ' unique permissions to create.');

        // 2. Create or get all permissions
        $permissionModels = [];
        foreach ($permissionNames as $name) {
            $permissionModels[$name] = Permission::firstOrCreate(
                ['name' => $name, 'guard_name' => 'business'],
                ['name' => $name, 'guard_name' => 'business']
            );
        }

        $this->command->info('RolePermissionSeeder: ' . count($permissionModels) . ' permissions ready in DB.');

        // 3. Collect all unique role names from the matrix
        $roleNamesFromMatrix = [];
        foreach ($this->permissionMatrix as [$module, $controller, $action, $roles]) {
            foreach ($roles as $role) {
                $roleNamesFromMatrix[$role] = true;
            }
        }

        // 4. Get all existing business roles from DB
        $allRoles = Role::where('guard_name', 'business')
            ->where('role_type', 'Business')
            ->get()
            ->keyBy('name');

        $this->command->info('RolePermissionSeeder: ' . count($allRoles) . ' roles found in DB.');

        // 5. Build role -> permissions mapping from matrix
        $rolePermissions = [];
        foreach ($this->permissionMatrix as [$module, $controller, $action, $roles]) {
            $permName = $this->buildPermissionName($module, $controller, $action);
            $permModel = $permissionModels[$permName];

            foreach ($roles as $roleName) {
                if (!isset($rolePermissions[$roleName])) {
                    $rolePermissions[$roleName] = [];
                }
                $rolePermissions[$roleName][] = $permModel;
            }
        }

        // 6. "Business" role (Level 0) gets ALL permissions
        if (isset($allRoles['Business'])) {
            $allPermModels = array_values($permissionModels);
            $allRoles['Business']->syncPermissions($allPermModels);
            $this->command->info('RolePermissionSeeder: Business (Level 0) synced with ALL ' . count($allPermModels) . ' permissions.');
        }

        // 7. Level 1 roles get 0 permissions
        $level1Roles = ['Business Staff', 'Business Clients', 'Business Contractor', 'Business Suppliers', 'Business Investors', 'Business Partners'];
        foreach ($level1Roles as $roleName) {
            if (isset($allRoles[$roleName])) {
                $allRoles[$roleName]->syncPermissions([]);
                $this->command->info('RolePermissionSeeder: ' . $roleName . ' (Level 1) synced with 0 permissions.');
            }
        }

        // 8. Level 2 roles get permissions per matrix
        foreach ($rolePermissions as $roleName => $perms) {
            if (isset($allRoles[$roleName])) {
                $allRoles[$roleName]->syncPermissions($perms);
                $this->command->info('RolePermissionSeeder: ' . $roleName . ' synced with ' . count($perms) . ' permissions.');
            } else {
                $this->command->warn('RolePermissionSeeder: Role "' . $roleName . '" not found in DB — skipped.');
            }
        }

        // Backfill permission descriptions from config (if column exists)
        if (\Schema::hasColumn('permissions', 'description')) {
            $descriptions = config('solarmitra.permission_description', []);
            $updated = 0;
            foreach ($permissionModels as $name => $permModel) {
                if (is_null($permModel->description) && isset($descriptions[$name])) {
                    $permModel->update(['description' => $descriptions[$name]]);
                    $updated++;
                }
            }
            if ($updated > 0) {
                $this->command->info('RolePermissionSeeder: ' . $updated . ' permission descriptions backfilled.');
            }
        }

        $this->command->info('RolePermissionSeeder: Done. Total ' . count($permissionModels) . ' permissions, ' . count($allRoles) . ' roles.');
    }

    /**
     * Build permission name matching the format from PermissionsController::add_to_permissions().
     * XLSX: SolarMitra > Business > Quotations > index
     * DB:   SolarMitra > Business > QuotationsController > index
     */
    private function buildPermissionName(string $module, string $controller, string $action): string
    {
        return 'SolarMitra > ' . $module . ' > ' . $controller . 'Controller > ' . $action;
    }
}
