<?php

return array (
  0 =>
  array (
    'id' => 59,
    'country_id' => 1,
    'language_id' => 30,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 30,
      'title' => 'Persian',
      'lang_title' => 'فارسی',
      'language_code' => 'fa',
      'country_id' => 1,
      'country' => 'Afghanistan',
      'country_code' => 'AF',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:47:50.000000Z',
    ),
    'country' =>
    array (
      'id' => 1,
      'iso_code' => 'AF',
      'title' => 'Afghanistan',
      'country_title' => 'Afghanistan',
      'phone' => '93',
      'currency_symbol' => '؋',
      'capital' => 'Kabul',
      'currency' => 'AFN',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'AFG',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T12:54:06.000000Z',
    ),
  ),
  1 =>
  array (
    'id' => 60,
    'country_id' => 1,
    'language_id' => 88,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 88,
      'title' => 'Pashto/Pushto',
      'lang_title' => 'پښتو/پښتو',
      'language_code' => 'ps',
      'country_id' => 1,
      'country' => 'Afghanistan',
      'country_code' => 'AF',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T13:23:20.000000Z',
    ),
    'country' =>
    array (
      'id' => 1,
      'iso_code' => 'AF',
      'title' => 'Afghanistan',
      'country_title' => 'Afghanistan',
      'phone' => '93',
      'currency_symbol' => '؋',
      'capital' => 'Kabul',
      'currency' => 'AFN',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'AFG',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T12:54:06.000000Z',
    ),
  ),
  2 =>
  array (
    'id' => 61,
    'country_id' => 2,
    'language_id' => 111,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 111,
      'title' => 'Swedish',
      'lang_title' => 'svenska',
      'language_code' => 'sv',
      'country_id' => 102,
      'country' => 'Iceland',
      'country_code' => 'IS',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-16T09:54:38.000000Z',
    ),
    'country' =>
    array (
      'id' => 2,
      'iso_code' => 'AX',
      'title' => 'Aland Islands',
      'country_title' => 'Åland Islands',
      'phone' => '358',
      'currency_symbol' => '€',
      'capital' => 'Mariehamn',
      'currency' => 'EUR',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'ALA',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:12:26.000000Z',
    ),
  ),
  3 =>
  array (
    'id' => 62,
    'country_id' => 3,
    'language_id' => 106,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 106,
      'title' => 'Albanian',
      'lang_title' => 'shqiptare',
      'language_code' => 'sq',
      'country_id' => 3,
      'country' => 'Albania',
      'country_code' => 'AL',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-23T12:59:44.000000Z',
    ),
    'country' =>
    array (
      'id' => 3,
      'iso_code' => 'AL',
      'title' => 'Albania',
      'country_title' => 'Shqipëria',
      'phone' => '355',
      'currency_symbol' => 'Lek',
      'capital' => 'Tirana',
      'currency' => 'ALL',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'ALB',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:13:19.000000Z',
    ),
  ),
  4 =>
  array (
    'id' => 63,
    'country_id' => 4,
    'language_id' => 6,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 6,
      'title' => 'Arabic',
      'lang_title' => 'عربي',
      'language_code' => 'ar',
      'country_id' => 11,
      'country' => 'Egypt',
      'country_code' => 'EG',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-23T12:55:18.000000Z',
    ),
    'country' =>
    array (
      'id' => 4,
      'iso_code' => 'DZ',
      'title' => 'Algeria',
      'country_title' => 'العربية',
      'phone' => '213',
      'currency_symbol' => 'دج',
      'capital' => 'Algiers',
      'currency' => 'DZD',
      'continent' => 'Africa',
      'continent_code' => 'AF',
      'iso3' => 'DZA',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:14:28.000000Z',
    ),
  ),

  7 =>
  array (
    'id' => 66,
    'country_id' => 5,
    'language_id' => 103,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 103,
      'title' => 'Samoan',
      'lang_title' => 'Atopao',
      'language_code' => 'sm',
      'country_id' => NULL,
      'country' => NULL,
      'country_code' => NULL,
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-13T12:07:52.000000Z',
    ),
    'country' =>
    array (
      'id' => 5,
      'iso_code' => 'AS',
      'title' => 'American Samoa',
      'country_title' => 'American Samoa',
      'phone' => '1684',
      'currency_symbol' => '$',
      'capital' => 'Pago Pago',
      'currency' => 'USD',
      'continent' => 'Oceania',
      'continent_code' => 'OC',
      'iso3' => 'ASM',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:16:00.000000Z',
    ),
  ),
  8 =>
  array (
    'id' => 67,
    'country_id' => 5,
    'language_id' => 1,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 5,
      'iso_code' => 'AS',
      'title' => 'American Samoa',
      'country_title' => 'American Samoa',
      'phone' => '1684',
      'currency_symbol' => '$',
      'capital' => 'Pago Pago',
      'currency' => 'USD',
      'continent' => 'Oceania',
      'continent_code' => 'OC',
      'iso3' => 'ASM',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:16:00.000000Z',
    ),
  ),
  9 =>
  array (
    'id' => 68,
    'country_id' => 6,
    'language_id' => 18,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 18,
      'title' => 'Catalan',
      'lang_title' => 'català',
      'language_code' => 'ca',
      'country_id' => 6,
      'country' => 'Andorra',
      'country_code' => 'AD',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-15T11:59:48.000000Z',
    ),
    'country' =>
    array (
      'id' => 6,
      'iso_code' => 'AD',
      'title' => 'Andorra',
      'country_title' => 'Andorra',
      'phone' => '376',
      'currency_symbol' => '€',
      'capital' => 'Andorra la Vella',
      'currency' => 'EUR',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'AND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:17:09.000000Z',
    ),
  ),
  10 =>
  array (
    'id' => 69,
    'country_id' => 6,
    'language_id' => 34,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 34,
      'title' => 'French',
      'lang_title' => 'Français',
      'language_code' => 'fr',
      'country_id' => 22,
      'country' => 'Belgium',
      'country_code' => 'BE',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:49:57.000000Z',
    ),
    'country' =>
    array (
      'id' => 6,
      'iso_code' => 'AD',
      'title' => 'Andorra',
      'country_title' => 'Andorra',
      'phone' => '376',
      'currency_symbol' => '€',
      'capital' => 'Andorra la Vella',
      'currency' => 'EUR',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'AND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:17:09.000000Z',
    ),
  ),
  11 =>
  array (
    'id' => 70,
    'country_id' => 7,
    'language_id' => 93,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 93,
      'title' => 'Romanian',
      'lang_title' => 'Română',
      'language_code' => 'ro',
      'country_id' => 147,
      'country' => 'Moldova, Republic of',
      'country_code' => 'MD',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T13:26:33.000000Z',
    ),
    'country' =>
    array (
      'id' => 7,
      'iso_code' => 'AO',
      'title' => 'Angola',
      'country_title' => 'अंगोला',
      'phone' => '244',
      'currency_symbol' => 'Kz',
      'capital' => 'Luanda',
      'currency' => 'AOA',
      'continent' => 'Africa',
      'continent_code' => 'AF',
      'iso3' => 'AGO',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:18:12.000000Z',
    ),
  ),
  12 =>
  array (
    'id' => 71,
    'country_id' => 8,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 8,
      'iso_code' => 'AI',
      'title' => 'Anguilla',
      'country_title' => 'Anguilla',
      'phone' => '1264',
      'currency_symbol' => '$',
      'capital' => 'The Valley',
      'currency' => 'XCD',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'AIA',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:18:51.000000Z',
    ),
  ),
  13 =>
  array (
    'id' => 72,
    'country_id' => 9,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 9,
      'iso_code' => 'AQ',
      'title' => 'Antarctica',
      'country_title' => 'Antarctica',
      'phone' => '672',
      'currency_symbol' => '$',
      'capital' => 'Antarctica',
      'currency' => 'AAD',
      'continent' => 'Antarctica',
      'continent_code' => 'AN',
      'iso3' => 'ATA',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:19:06.000000Z',
    ),
  ),
  14 =>
  array (
    'id' => 73,
    'country_id' => 10,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 10,
      'iso_code' => 'AG',
      'title' => 'Antigua and Barbuda',
      'country_title' => 'Antigua and Barbuda',
      'phone' => '1268456555',
      'currency_symbol' => '$',
      'capital' => 'St. John\'s',
      'currency' => 'XCD',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'ATG',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:19:45.000000Z',
    ),
  ),
  15 =>
  array (
    'id' => 74,
    'country_id' => 103,
    'language_id' => 42,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 42,
      'title' => 'Hindi',
      'lang_title' => 'हिंदी',
      'language_code' => 'hi',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-23T12:18:50.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  16 =>
  array (
    'id' => 75,
    'country_id' => 103,
    'language_id' => 7,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 7,
      'title' => 'Assamese',
      'lang_title' => 'অসমীয়া',
      'language_code' => 'as',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '1',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-23T13:01:00.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  17 =>
  array (
    'id' => 76,
    'country_id' => 103,
    'language_id' => 13,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 13,
      'title' => 'Bihari',
      'lang_title' => 'বিহাৰী',
      'language_code' => 'bh',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '1',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-15T05:14:48.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  18 =>
  array (
    'id' => 77,
    'country_id' => 103,
    'language_id' => 15,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 15,
      'title' => 'Bengali/Bangla',
      'lang_title' => 'বাংলা/বাংলা',
      'language_code' => 'bn',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:37:28.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  19 =>
  array (
    'id' => 78,
    'country_id' => 103,
    'language_id' => 40,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 40,
      'title' => 'Gujarati',
      'lang_title' => 'ગુજરાતી',
      'language_code' => 'gu',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:53:35.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  20 =>
  array (
    'id' => 79,
    'country_id' => 103,
    'language_id' => 60,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 60,
      'title' => 'Kannada',
      'lang_title' => 'ಕನ್ನಡ',
      'language_code' => 'kn',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T12:30:37.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  21 =>
  array (
    'id' => 80,
    'country_id' => 103,
    'language_id' => 62,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 62,
      'title' => 'Kashmiri',
      'lang_title' => 'كٲشُر',
      'language_code' => 'ks',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T12:32:15.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  22 =>
  array (
    'id' => 81,
    'country_id' => 103,
    'language_id' => 73,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 73,
      'title' => 'Malayalam',
      'lang_title' => 'മലയാളം',
      'language_code' => 'ml',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T13:03:01.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  23 =>
  array (
    'id' => 82,
    'country_id' => 103,
    'language_id' => 76,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 76,
      'title' => 'Marathi',
      'lang_title' => 'मराठी',
      'language_code' => 'mr',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T13:04:19.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  24 =>
  array (
    'id' => 83,
    'country_id' => 103,
    'language_id' => 86,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 86,
      'title' => 'Punjabi',
      'lang_title' => 'ਪੰਜਾਬੀ',
      'language_code' => 'pa',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T13:22:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  25 =>
  array (
    'id' => 84,
    'country_id' => 103,
    'language_id' => 96,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 96,
      'title' => 'Sanskrit',
      'lang_title' => 'संस्कृत',
      'language_code' => 'sa',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-15T07:04:02.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  26 =>
  array (
    'id' => 85,
    'country_id' => 103,
    'language_id' => 97,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 97,
      'title' => 'Sindhi',
      'lang_title' => 'سنڌي',
      'language_code' => 'sd',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T13:28:11.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  27 =>
  array (
    'id' => 86,
    'country_id' => 103,
    'language_id' => 114,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 114,
      'title' => 'Telugu',
      'lang_title' => 'இந்தியா',
      'language_code' => 'te',
      'country_id' => NULL,
      'country' => NULL,
      'country_code' => NULL,
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-13T12:07:52.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  28 =>
  array (
    'id' => 87,
    'country_id' => 103,
    'language_id' => 127,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 127,
      'title' => 'Urdu',
      'lang_title' => 'اردو',
      'language_code' => 'ur',
      'country_id' => 170,
      'country' => 'Pakistan',
      'country_code' => 'PK',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-15T12:45:56.000000Z',
    ),
    'country' =>
    array (
      'id' => 103,
      'iso_code' => 'IN',
      'title' => 'India',
      'country_title' => 'भारत',
      'phone' => '91',
      'currency_symbol' => '₹',
      'capital' => 'New Delhi',
      'currency' => 'INR',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IND',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-09-29T15:26:34.000000Z',
    ),
  ),
  29 =>
  array (
    'id' => 88,
    'country_id' => 33,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 33,
      'iso_code' => 'IO',
      'title' => 'British Indian Ocean Territory',
      'country_title' => 'British Indian Ocean Territory',
      'phone' => '246',
      'currency_symbol' => '$',
      'capital' => 'Diego Garcia',
      'currency' => 'USD',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'IOT',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:23:35.000000Z',
    ),
  ),
  30 =>
  array (
    'id' => 89,
    'country_id' => 11,
    'language_id' => 27,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 27,
      'title' => 'Spanish',
      'lang_title' => 'española',
      'language_code' => 'es',
      'country_id' => 212,
      'country' => 'Spain',
      'country_code' => 'ES',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:45:58.000000Z',
    ),
    'country' =>
    array (
      'id' => 11,
      'iso_code' => 'AR',
      'title' => 'Argentina',
      'country_title' => 'Argentina',
      'phone' => '54',
      'currency_symbol' => '$',
      'capital' => 'Buenos Aires',
      'currency' => 'ARS',
      'continent' => 'South America',
      'continent_code' => 'SA',
      'iso3' => 'ARG',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:25:06.000000Z',
    ),
  ),
  31 =>
  array (
    'id' => 90,
    'country_id' => 12,
    'language_id' => 45,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 45,
      'title' => 'Armenian',
      'lang_title' => 'հայերեն',
      'language_code' => 'hy',
      'country_id' => 12,
      'country' => 'Armenia',
      'country_code' => 'AM',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:29:05.000000Z',
    ),
    'country' =>
    array (
      'id' => 12,
      'iso_code' => 'AM',
      'title' => 'Armenia',
      'country_title' => 'Armenian',
      'phone' => '374',
      'currency_symbol' => '֏',
      'capital' => 'Yerevan',
      'currency' => 'AMD',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'ARM',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:25:57.000000Z',
    ),
  ),
  32 =>
  array (
    'id' => 91,
    'country_id' => 13,
    'language_id' => 27,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 27,
      'title' => 'Spanish',
      'lang_title' => 'española',
      'language_code' => 'es',
      'country_id' => 212,
      'country' => 'Spain',
      'country_code' => 'ES',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:45:58.000000Z',
    ),
    'country' =>
    array (
      'id' => 13,
      'iso_code' => 'AW',
      'title' => 'Aruba',
      'country_title' => 'Aruba',
      'phone' => '297',
      'currency_symbol' => 'ƒ',
      'capital' => 'Oranjestad',
      'currency' => 'AWG',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'ABW',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:27:01.000000Z',
    ),
  ),
  33 =>
  array (
    'id' => 92,
    'country_id' => 14,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 14,
      'iso_code' => 'AU',
      'title' => 'Australia',
      'country_title' => 'Australia',
      'phone' => '61',
      'currency_symbol' => '$',
      'capital' => 'Canberra',
      'currency' => 'AUD',
      'continent' => 'Oceania',
      'continent_code' => 'OC',
      'iso3' => 'AUS',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:27:21.000000Z',
    ),
  ),
  34 =>
  array (
    'id' => 93,
    'country_id' => 15,
    'language_id' => 23,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 23,
      'title' => 'German',
      'lang_title' => 'Deutsch',
      'language_code' => 'de',
      'country_id' => 83,
      'country' => 'Germany',
      'country_code' => 'DE',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:42:23.000000Z',
    ),
    'country' =>
    array (
      'id' => 15,
      'iso_code' => 'AT',
      'title' => 'Austria',
      'country_title' => 'Österreich',
      'phone' => '43',
      'currency_symbol' => '€',
      'capital' => 'Vienna',
      'currency' => 'EUR',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'AUT',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:28:05.000000Z',
    ),
  ),
  35 =>
  array (
    'id' => 94,
    'country_id' => 16,
    'language_id' => 9,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 9,
      'title' => 'Azerbaijani',
      'lang_title' => 'Azərbaycanca',
      'language_code' => 'az',
      'country_id' => 16,
      'country' => 'Azerbaijan',
      'country_code' => 'AZ',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:32:06.000000Z',
    ),
    'country' =>
    array (
      'id' => 16,
      'iso_code' => 'AZ',
      'title' => 'Azerbaijan',
      'country_title' => 'Azərbaycan',
      'phone' => '994',
      'currency_symbol' => 'm',
      'capital' => 'Baku',
      'currency' => 'AZN',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'AZE',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:28:59.000000Z',
    ),
  ),
  36 =>
  array (
    'id' => 95,
    'country_id' => 17,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 17,
      'iso_code' => 'BS',
      'title' => 'Bahamas',
      'country_title' => 'Bahamas',
      'phone' => '1242',
      'currency_symbol' => 'B$',
      'capital' => 'Nassau',
      'currency' => 'BSD',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'BHS',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:29:34.000000Z',
    ),
  ),
  37 =>
  array (
    'id' => 96,
    'country_id' => 18,
    'language_id' => 6,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 6,
      'title' => 'Arabic',
      'lang_title' => 'عربي',
      'language_code' => 'ar',
      'country_id' => 11,
      'country' => 'Egypt',
      'country_code' => 'EG',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-23T12:55:18.000000Z',
    ),
    'country' =>
    array (
      'id' => 18,
      'iso_code' => 'BH',
      'title' => 'Bahrain',
      'country_title' => 'البحرين',
      'phone' => '973',
      'currency_symbol' => '.د.ب',
      'capital' => 'Manama',
      'currency' => 'BHD',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'BHR',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T12:58:00.000000Z',
    ),
  ),
  38 =>
  array (
    'id' => 97,
    'country_id' => 19,
    'language_id' => 15,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 15,
      'title' => 'Bengali/Bangla',
      'lang_title' => 'বাংলা/বাংলা',
      'language_code' => 'bn',
      'country_id' => 103,
      'country' => 'India',
      'country_code' => 'IN',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:37:28.000000Z',
    ),
    'country' =>
    array (
      'id' => 19,
      'iso_code' => 'BD',
      'title' => 'Bangladesh',
      'country_title' => 'বাংলাদেশ',
      'phone' => '880',
      'currency_symbol' => '৳',
      'capital' => 'Dhaka',
      'currency' => 'BDT',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'BGD',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T12:58:48.000000Z',
    ),
  ),
  39 =>
  array (
    'id' => 98,
    'country_id' => 20,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 20,
      'iso_code' => 'BB',
      'title' => 'Barbados',
      'country_title' => 'Barbados',
      'phone' => '1246',
      'currency_symbol' => 'Bds$',
      'capital' => 'Bridgetown',
      'currency' => 'BBD',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'BRB',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T12:59:24.000000Z',
    ),
  ),
  40 =>
  array (
    'id' => 99,
    'country_id' => 21,
    'language_id' => 11,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 11,
      'title' => 'Belarusian',
      'lang_title' => 'Беларусь',
      'language_code' => 'be',
      'country_id' => 21,
      'country' => 'Belarus',
      'country_code' => 'BY',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:26:05.000000Z',
    ),
    'country' =>
    array (
      'id' => 21,
      'iso_code' => 'BY',
      'title' => 'Belarus',
      'country_title' => 'Беларусь',
      'phone' => '375',
      'currency_symbol' => 'Br',
      'capital' => 'Minsk',
      'currency' => 'BYN',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'BLR',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:00:21.000000Z',
    ),
  ),
  41 =>
  array (
    'id' => 100,
    'country_id' => 22,
    'language_id' => 82,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 82,
      'title' => 'Dutch',
      'lang_title' => 'Tutsi',
      'language_code' => 'nl',
      'country_id' => 22,
      'country' => 'Belgium',
      'country_code' => 'BE',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T13:19:07.000000Z',
    ),
    'country' =>
    array (
      'id' => 22,
      'iso_code' => 'BE',
      'title' => 'Belgium',
      'country_title' => 'België',
      'phone' => '32',
      'currency_symbol' => '€',
      'capital' => 'Brussels',
      'currency' => 'EUR',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'BEL',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:34:02.000000Z',
    ),
  ),
  42 =>
  array (
    'id' => 101,
    'country_id' => 22,
    'language_id' => 23,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 23,
      'title' => 'German',
      'lang_title' => 'Deutsch',
      'language_code' => 'de',
      'country_id' => 83,
      'country' => 'Germany',
      'country_code' => 'DE',
      'is_universal' => NULL,
      'is_main' => '1',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:42:23.000000Z',
    ),
    'country' =>
    array (
      'id' => 22,
      'iso_code' => 'BE',
      'title' => 'Belgium',
      'country_title' => 'België',
      'phone' => '32',
      'currency_symbol' => '€',
      'capital' => 'Brussels',
      'currency' => 'EUR',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'BEL',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:34:02.000000Z',
    ),
  ),
  43 =>
  array (
    'id' => 102,
    'country_id' => 22,
    'language_id' => 34,
    'lang_type' => 'regional',
    'language' =>
    array (
      'id' => 34,
      'title' => 'French',
      'lang_title' => 'Français',
      'language_code' => 'fr',
      'country_id' => 22,
      'country' => 'Belgium',
      'country_code' => 'BE',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:49:57.000000Z',
    ),
    'country' =>
    array (
      'id' => 22,
      'iso_code' => 'BE',
      'title' => 'Belgium',
      'country_title' => 'België',
      'phone' => '32',
      'currency_symbol' => '€',
      'capital' => 'Brussels',
      'currency' => 'EUR',
      'continent' => 'Europe',
      'continent_code' => 'EU',
      'iso3' => 'BEL',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:34:02.000000Z',
    ),
  ),
  44 =>
  array (
    'id' => 103,
    'country_id' => 23,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 23,
      'iso_code' => 'BZ',
      'title' => 'Belize',
      'country_title' => 'Belize',
      'phone' => '501',
      'currency_symbol' => '$',
      'capital' => 'Belmopan',
      'currency' => 'BZD',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'BLZ',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:34:40.000000Z',
    ),
  ),
  45 =>
  array (
    'id' => 104,
    'country_id' => 24,
    'language_id' => 34,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 34,
      'title' => 'French',
      'lang_title' => 'Français',
      'language_code' => 'fr',
      'country_id' => 22,
      'country' => 'Belgium',
      'country_code' => 'BE',
      'is_universal' => NULL,
      'is_main' => '0',
      'is_regional' => '0',
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-14T06:49:57.000000Z',
    ),
    'country' =>
    array (
      'id' => 24,
      'iso_code' => 'BJ',
      'title' => 'Benin',
      'country_title' => 'Bénin',
      'phone' => '229',
      'currency_symbol' => 'CFA',
      'capital' => 'Porto-Novo',
      'currency' => 'XOF',
      'continent' => 'Africa',
      'continent_code' => 'AF',
      'iso3' => 'BEN',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:35:29.000000Z',
    ),
  ),
  46 =>
  array (
    'id' => 105,
    'country_id' => 25,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' =>
    array (
      'id' => 25,
      'iso_code' => 'BM',
      'title' => 'Bermuda',
      'country_title' => 'Bermuda',
      'phone' => '1441',
      'currency_symbol' => '$',
      'capital' => 'Hamilton',
      'currency' => 'BMD',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'BMU',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:36:57.000000Z',
    ),
  ),
  47 =>
  array (
    'id' => 106,
    'country_id' => 26,
    'language_id' => 197,
    'lang_type' => 'main',
    'language' =>
    array (
      'id' => 197,
      'title' => 'Dzongkha',
      'lang_title' => 'भूटान',
      'language_code' => 'DZ',
      'country_id' => NULL,
      'country' => NULL,
      'country_code' => NULL,
      'is_universal' => '0',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'inactive',
      'created_at' => '2023-10-02T13:41:33.000000Z',
      'updated_at' => '2023-10-02T13:41:33.000000Z',
    ),
    'country' =>
    array (
      'id' => 26,
      'iso_code' => 'BT',
      'title' => 'Bhutan',
      'country_title' => 'भूटान',
      'phone' => '975',
      'currency_symbol' => 'Nu.',
      'capital' => 'Thimphu',
      'currency' => 'BTN',
      'continent' => 'Asia',
      'continent_code' => 'AS',
      'iso3' => 'BTN',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-02T13:43:25.000000Z',
    ),
  ),
  48 => 
  array (
    'id' => 107,
    'country_id' => 239,
    'language_id' => 1,
    'lang_type' => 'main',
    'language' => 
    array (
      'id' => 1,
      'title' => 'English',
      'lang_title' => 'English',
      'language_code' => 'en',
      'country_id' => 14,
      'country' => 'Australia',
      'country_code' => 'AU',
      'is_universal' => '1',
      'is_main' => '1',
      'is_regional' => NULL,
      'status' => 'active',
      'created_at' => '2023-09-12T16:31:17.000000Z',
      'updated_at' => '2023-09-30T08:27:03.000000Z',
    ),
    'country' => 
    array (
      'id' => 239,
      'iso_code' => 'US',
      'title' => 'United States',
      'country_title' => 'United States',
      'phone' => '1',
      'currency_symbol' => '$',
      'capital' => 'Washington',
      'currency' => 'USD',
      'continent' => 'North America',
      'continent_code' => 'NA',
      'iso3' => 'USA',
      'status' => 'active',
      'created_at' => '2023-09-29T15:26:15.000000Z',
      'updated_at' => '2023-10-03T07:28:51.000000Z',
    ),
  ),
);
